config/routes.rb
EtCms::Engine.routes.draw do
  root to: "pages#home", :via => :get
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, {
      class_name: 'EtCms::User',
      module: :devise,
  }

  get '/pages/home'
  get '/pages/:id', :to => 'pages#show', :as => :page

  namespace :admin do
    root to: "pages#index"
    resources :pages
    resources :user, :controller => "user"

  end

  resources :pages
  resources :pages, :path => ''
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    {}.merge(PAPERCLIP_STORAGE_OPTIONS)
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    {:styles => { :content => '800>', :thumb => '118x100#' }}.merge(PAPERCLIP_STORAGE_OPTIONS)
	
	validates_attachment_size :data, :less_than => 5.megabytes
	validates_attachment_presence :data
	
	def url_content
	  url(:content)
	end
end

app/models/et_cms/page.rb
module EtCms
  class Page < ActiveRecord::Base
    has_ancestry
    attr_accessible :browser_title, :content, :exclude_from_menu, :link_url, :list_order, :meta_description,
                    :name, :parent_id, :active

    extend FriendlyId
    friendly_id :name, use: :slugged
    validates_uniqueness_of :name
    validates_uniqueness_of :browser_title

    def breadcrumbs
      breadcrumb = %Q(<a href="#{self.slug}">#{self.name}</a>)
      parent_id = self.parent_id
      while (!parent_id.nil?)
        puts parent_id
        parent = Page.find(parent_id)
        breadcrumb = %Q(<a href="#{parent.slug}">#{parent.name}</a>) + " > " + breadcrumb
        parent_id = parent.parent_id
      end
      breadcrumb
    end
  end
end

app/models/et_cms/user.rb
module EtCms
  class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :token_authenticatable, :confirmable,
    # :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  
    # Setup accessible (or protected) attributes for your model
    attr_accessible :email, :password, :password_confirmation, :remember_me
    # attr_accessible :title, :body

    after_create { |user| user.send_reset_password_instructions if user.password.nil? } unless ['test'].include? Rails.env

    def password_required?
      new_record? ? false : super
    end
  end
end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base

  end

app/controllers/et_cms/admin/pages_controller.rb
module EtCms
  module Admin
    class PagesController < EtCms::AdminController

      def index
        @menu_pages = Page.where(:exclude_from_menu => false, :ancestry => nil).order("list_order ASC")
      end

      def new
        @pages = Page.all
        @page = Page.new
      end

      def edit
        @pages = Page.all
        @page = Page.find(params[:id])
      end

      def create
        @page = Page.new(params[:page])

        if @page.save
          redirect_to(admin_pages_url, :notice => 'Page was successfully created.')
        else
          @pages = Page.all
          render :action => "new"
        end
      end

      def update
        @page = Page.find(params[:id])

        respond_to do |format|
          if @page.update_attributes(params[:page])
            format.html { redirect_to(admin_pages_url, :notice => 'Page was successfully updated.') }
            format.json { head :ok }
          else
            @pages = Page.all
            format.html { render :action => "edit" }
            format.json { head :bad_request }
          end
        end
      end

      def destroy
        Page.destroy(params[:id])
        redirect_to(admin_pages_url)
      end
    end
  end
end

app/controllers/et_cms/admin/user_controller.rb
module EtCms
  module Admin
    class UserController < EtCms::AdminController
      def index
        @users = User.all
      end

      def new
        @user = User.new
      end

      def create
        @user = User.new(params[:user])

        if @user.save
          redirect_to(admin_user_index_url, :notice => 'User was successfully created.')
        else
          render :action => "new"
        end
      end

      def edit
        @user = User.find(current_user)
      end

      def update
        @user = User.find(current_user)
        params[:user].delete(:password) if params[:user][:password].blank?
        params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
        if @user.update_attributes(params[:user])
          flash[:notice] = "Successfully updated User."
          redirect_to admin_user_index_url
        else
          render :action => 'edit'
        end
      end

      def destroy
        @user = User.find(params[:id])
        if @user.destroy
          flash[:notice] = "Successfully deleted User."
          redirect_to admin_user_index_url
        end
      end
    end
  end
end

app/controllers/et_cms/admin_controller.rb
module EtCms
  class AdminController < ApplicationController
    before_filter :authenticate_user!
  end
end

app/controllers/et_cms/application_controller.rb
module EtCms
  class ApplicationController < ActionController::Base

  end
end

app/controllers/et_cms/pages_controller.rb
module EtCms
  class PagesController < ApplicationController

    def home
      @page = Page.find("home")
      render "show"
    end


    def show
      @page = Page.find(params[:id].downcase)
    end

  end
end

app/helpers/et_cms/admin/user_helper.rb
module EtCms
  module Admin::UserHelper
  end
end

app/helpers/et_cms/admin_helper.rb
module EtCms
  module AdminHelper
  end
end

app/helpers/et_cms/application_helper.rb
module EtCms
  module ApplicationHelper
  end
end

app/helpers/et_cms/pages_helper.rb
module EtCms
  module PagesHelper
  end
end

app/views/et_cms/admin/pages/_form.html.erb
<%= semantic_form_for [:admin,@page] do |f| %>
    <%= f.input :name %>
    <%= f.input :browser_title %>
    <%= f.input :content, :as => :ckeditor, :input_html => {:height => 400}, :label => false %>
    <%= f.input :parent_id, :as => :select, :collection => Hash[@pages.map{|b| [b.name,b.id] unless b.depth > 4}] %>
    <%= f.input :meta_description %>
    <%= f.label :exclude_from_menu, :class => "left" %>
    <%= f.check_box :exclude_from_menu %>
    <div style="clear:both;"></div>
    <%= f.input :link_url %>
    <%= f.input :list_order %>
    <%= f.label :active, :class => "left" %>
    <%= f.check_box :active %>

    <%= f.actions do %>
        <%= f.action :submit, :as => :button, :button_html => {:class => "btn btn-success"} %>
        <%= f.action :cancel, :as => :link, :button_html => {:class => "btn btn-warning"} %>
    <% end %>
<% end %>

app/views/et_cms/admin/pages/edit.html.erb
<%= render "form" %>

app/views/et_cms/admin/pages/index.html.erb
<%= link_to "New Page", new_admin_page_path, :class => "btn btn-primary" %>

<table class="table">
  <thead>
  <tr>
    <th>Page</th>
    <th>Active</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @menu_pages.each do |menu_page| %>
      <% menu_page.subtree.each do |page| %>
          <tr>
            <td style="padding-left: <%= "#{page.depth * 20}px" %>;"><%= page.name %></td>
            <td><%= page.active? ? "Yes" : "No" %></td>
            <td>
              <%= link_to 'View', "/#{page.name}" %>&nbsp;|&nbsp; <%= link_to 'Edit', edit_admin_page_path(page) %>&nbsp;|&nbsp;<%= link_to 'Delete', admin_page_path(page), :confirm => "Are you sure?", :method => :delete %>
            </td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/et_cms/admin/pages/new.html.erb
<%= render "form" %>

app/views/et_cms/admin/user/edit.html.erb
<%= semantic_form_for @user, :url => admin_user_path(@user), :method => :put do |f| %>
    <%= f.input :email %>

    <%= f.input :password %>
    <%= f.input :password_confirmation %>


    <%= f.actions do %>
        <%= f.action :submit, :as => :button, :button_html => {:class => "btn btn-success"} %>
        <%= f.action :cancel, :as => :link, :button_html => {:class => "btn btn-warning"} %>
    <% end %>
<% end %>

app/views/et_cms/admin/user/index.html.erb
<%= link_to "New User", new_admin_user_path, :class => "btn btn-primary" %>

<table class="table">
  <thead>
  <tr>
    <th>Email</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td>
          <% if current_user == user %>
              <%= link_to 'Edit', edit_admin_user_path(user) %>
          <% else %>
              <%= link_to 'Delete', admin_user_path(user), :confirm => "Are you sure?", :method => :delete %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/et_cms/admin/user/new.html.erb
<%= semantic_form_for @user, :url => "/admin/user", :method => :post do |f| %>
    <%= f.input :email %>

    <%= f.actions do %>
        <%= f.action :submit, :as => :button, :button_html => {:class => "btn btn-success"} %>
        <%= f.action :cancel, :as => :link, :button_html => {:class => "btn btn-warning"} %>
    <% end %>
<% end %>

app/views/et_cms/pages/_form.html.erb
<%= semantic_form_for @page do |f| %>
    <%= f.input :name %>
    <%= f.input :browser_title %>
    <%= f.input :content, :as => :ckeditor, :input_html => {:height => 400}, :label => false %>
    <%= f.input :parent_id %>
    <%= f.input :meta_description %>
    <%= f.label :exclude_from_menu, :class => "left" %>
    <%= f.check_box :exclude_from_menu %>
    <div style="clear:both;"></div>
    <%= f.input :link_url %>
    <%= f.input :list_order %>
    <%= f.input :status %>

    <%= f.actions do %>
        <%= f.action :submit, :as => :button, :button_html => {:class => "btn btn-success"} %>
        <%= f.action :cancel, :as => :link, :button_html => {:class => "btn btn-warning"} %>
    <% end %>
<% end %>

app/views/et_cms/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/et_cms/pages/home.html.erb</p>

app/views/et_cms/pages/show.html.erb
<%= @page.content.html_safe %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Sweet Company Here</title>
  <%= stylesheet_link_tag "et_cms/application", :media => "all" %>
  <%= javascript_include_tag "et_cms/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">The Next Big Thing</a>

      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Home", "/" %></li>

        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>
<p class="notice"><%= notice %></p>

<% unless alert.nil? %>
    <p class="alert"><%= alert %></p>
<% end %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EtCms</title>
  <%= stylesheet_link_tag "et_cms/application", :media => "all" %>
  <%= javascript_include_tag "et_cms/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">ET CMS</a>

      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Pages", et_cms.admin_pages_path %></li>
          <li><%= link_to "Users", et_cms.admin_user_index_path %></li>
          <li><%= link_to("Logout", et_cms.destroy_user_session_path, :method => :delete) %></li>
          <li> <%= link_to "Change your password", et_cms.edit_user_registration_path %></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<p class="notice"><%= notice %></p>

<% unless alert.nil? %>
    <p class="alert"><%= alert %></p>
<% end %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/et_cms/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EtCms</title>
  <%= stylesheet_link_tag "et_cms/application", :media => "all" %>
  <%= javascript_include_tag "et_cms/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">ET CMS</a>

      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Pages", "/admin/pages" %></li>
          <li><%= link_to "Users", "/admin/user" %></li>
          <li><%= link_to("Logout", "/users/sign_out", :method => :delete) %></li>
          <li> <%= link_to "Change your password", "/users/edit" %></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<p class="notice"><%= notice %></p>

<% unless alert.nil? %>
    <p class="alert"><%= alert %></p>
<% end %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>